import { Scale, FileText, ShieldAlert, CheckCircle2, Globe, Building2, HelpCircle } from 'lucide-react';
import { SEO } from '@/components/layout/SEO';
import { Link } from 'react-router-dom';

export default function TermsOfService() {
  return (
    <div className="py-20 px-4 max-w-4xl mx-auto">
      <SEO 
        title="Terms & Conditions | ForenClue"
        description="ForenClue Terms & Conditions. Review official terms of use, legal notices under Information Technology Act 2000, and user obligations for https://forenclue.in."
        keywords="forenclue terms and conditions, terms of use, forenclue ventures legal, electronic record it act"
        canonicalPath="/terms"
      />

      <div className="text-center mb-16">
        <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-warning/10 border border-warning/20 mb-6 shadow-[0_0_30px_rgba(255,165,0,0.2)]">
          <Scale className="text-warning" size={32} />
        </div>
        <h1 className="text-4xl md:text-5xl font-heading font-black mb-4 uppercase tracking-tight">
          Terms & <span className="text-warning">Conditions</span>
        </h1>
        <p className="text-text-muted text-sm max-w-2xl mx-auto">
          Domain: <a href="https://forenclue.in" className="text-warning hover:underline font-medium">https://forenclue.in</a> | Owned & Operated by ForenClue Ventures, Pune, Maharashtra
        </p>
      </div>

      <div className="space-y-10 text-base text-text-muted leading-relaxed">
        
        {/* Preamble / Electronic Record Notice */}
        <section className="bg-surface p-8 border border-black/10 dark:border-white/10 relative overflow-hidden rounded-xl space-y-4">
          <div className="absolute top-0 right-0 w-32 h-32 bg-warning/5 rounded-full blur-[50px] -z-10"></div>
          
          <div className="flex items-center gap-2 text-warning font-bold text-xs uppercase tracking-wider">
            <FileText size={16} />
            <span>Legal Notice & Electronic Record Declaration</span>
          </div>

          <p className="text-sm">
            1. This document is an electronic record in terms of <strong>Information Technology Act, 2000</strong> and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>
          <p className="text-sm">
            2. This document is published in accordance with the provisions of <strong>Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011</strong> that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <a href="https://forenclue.in" className="text-warning hover:underline font-medium">https://forenclue.in</a> (&apos;Website&apos;), including the related mobile site and mobile application (hereinafter referred to as &apos;Platform&apos;).
          </p>
          <p className="text-sm">
            3. The Platform is owned by <strong>ForenClue Ventures</strong>, a company incorporated under the Companies Act, 1956 with its registered office at <strong>Pune, Maharashtra</strong> (hereinafter referred to as &apos;Platform Owner&apos;, &apos;we&apos;, &apos;us&apos;, &apos;our&apos;).
          </p>
          <p className="text-sm">
            4. Your use of the Platform and services and tools are governed by the following terms and conditions (&quot;Terms of Use&quot;) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, &apos;Services&apos;). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
          </p>
          <p className="text-sm">
            5. For the purpose of these Terms of Use, wherever the context so requires &apos;you&apos;, &apos;your&apos; or &apos;user&apos; shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
          </p>
          
          <div className="p-4 bg-warning/10 border border-warning/30 rounded-lg text-xs font-bold text-text-main tracking-wide uppercase">
            6. ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
          </div>
        </section>

        {/* Section 7: Detailed Terms of Use Clauses */}
        <section className="bg-surface p-8 border border-black/10 dark:border-white/10 rounded-xl space-y-6">
          <h2 className="text-2xl font-heading font-bold text-text-main uppercase tracking-wide">
            7. Terms of Platform Access & Availing Services
          </h2>
          <p className="text-sm">
            The use of Platform and/or availing of our Services is subject to the following Terms of Use:
          </p>

          <div className="space-y-4 text-sm">
            <div className="flex items-start gap-3 p-4 bg-base/50 rounded-lg border border-black/5 dark:border-white/5">
              <span className="font-bold text-warning shrink-0 text-sm">7.1</span>
              <p>
                To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.
              </p>
            </div>

            <div className="flex items-start gap-3 p-4 bg-base/50 rounded-lg border border-black/5 dark:border-white/5">
              <span className="font-bold text-warning shrink-0 text-sm">7.2</span>
              <p>
                Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
              </p>
            </div>

            <div className="flex items-start gap-3 p-4 bg-base/50 rounded-lg border border-black/5 dark:border-white/5">
              <span className="font-bold text-warning shrink-0 text-sm">7.3</span>
              <p>
                Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.
              </p>
            </div>

            <div className="flex items-start gap-3 p-4 bg-base/50 rounded-lg border border-black/5 dark:border-white/5">
              <span className="font-bold text-warning shrink-0 text-sm">7.4</span>
              <p>
                The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.
              </p>
            </div>

            <div className="flex items-start gap-3 p-4 bg-base/50 rounded-lg border border-black/5 dark:border-white/5">
              <span className="font-bold text-warning shrink-0 text-sm">7.5</span>
              <p>
                You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.
              </p>
            </div>

            <div className="flex items-start gap-3 p-4 bg-base/50 rounded-lg border border-black/5 dark:border-white/5">
              <span className="font-bold text-warning shrink-0 text-sm">7.6</span>
              <p>
                You agree to pay us the charges associated with availing the Services.
              </p>
            </div>

            <div className="flex items-start gap-3 p-4 bg-base/50 rounded-lg border border-black/5 dark:border-white/5">
              <span className="font-bold text-warning shrink-0 text-sm">7.7</span>
              <p>
                You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.
              </p>
            </div>

            <div className="flex items-start gap-3 p-4 bg-base/50 rounded-lg border border-black/5 dark:border-white/5">
              <span className="font-bold text-warning shrink-0 text-sm">7.8</span>
              <p>
                You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information.
              </p>
            </div>

            <div className="flex items-start gap-3 p-4 bg-base/50 rounded-lg border border-black/5 dark:border-white/5">
              <span className="font-bold text-warning shrink-0 text-sm">7.9</span>
              <p>
                You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.
              </p>
            </div>
          </div>
        </section>

        {/* Section 8 to 14: Indemnity, Force Majeure, Jurisdiction & Notices */}
        <section className="bg-surface p-8 border border-black/10 dark:border-white/10 rounded-xl space-y-6">
          <h2 className="text-2xl font-heading font-bold text-text-main uppercase tracking-wide">
            Legal Obligations, Governing Law & Jurisdiction
          </h2>

          <div className="space-y-4 text-sm">
            <div className="p-4 bg-base/50 rounded-lg border border-black/5 dark:border-white/5 space-y-1">
              <h3 className="font-bold text-text-main">10. Indemnification</h3>
              <p>
                You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney&apos;s fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.
              </p>
            </div>

            <div className="p-4 bg-base/50 rounded-lg border border-black/5 dark:border-white/5 space-y-1">
              <h3 className="font-bold text-text-main">11. Force Majeure</h3>
              <p>
                Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
              </p>
            </div>

            <div className="p-4 bg-base/50 rounded-lg border border-black/5 dark:border-white/5 space-y-1">
              <h3 className="font-bold text-text-main">12. Governing Law</h3>
              <p>
                These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.
              </p>
            </div>

            <div className="p-4 bg-base/50 rounded-lg border border-black/5 dark:border-white/5 space-y-1">
              <h3 className="font-bold text-text-main">13. Jurisdiction</h3>
              <p>
                All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Pune, Maharashtra, India.
              </p>
            </div>

            <div className="p-4 bg-base/50 rounded-lg border border-black/5 dark:border-white/5 space-y-1">
              <h3 className="font-bold text-text-main">14. Communications & Notices</h3>
              <p>
                All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website (<Link to="/contact" className="text-warning hover:underline">Contact Page</Link> or email to <a href="mailto:support@forenclue.in" className="text-warning hover:underline">support@forenclue.in</a> / <a href="mailto:forenclue@gmail.com" className="text-warning hover:underline">forenclue@gmail.com</a>).
              </p>
            </div>
          </div>
        </section>

        {/* DMCA Badge & Verification Footer */}
        <section className="p-6 bg-surface border border-black/10 dark:border-white/10 rounded-xl flex flex-col sm:flex-row items-center justify-between gap-4">
          <div>
            <h4 className="font-bold text-text-main text-sm">DMCA.com Active Copyright Protection</h4>
            <p className="text-xs text-text-muted">Digital forensic instructional assets on forenclue.in are copyrighted and monitored.</p>
          </div>
          <a 
            href="https://www.dmca.com/r/8eqg90g" 
            target="_blank" 
            rel="noopener noreferrer"
            className="shrink-0"
          >
            <img 
              src="https://images.dmca.com/Badges/DMCA_logo-grn-btn120w.png?ID=cf5061f2-85e0-4a93-981a-645cfa86336c" 
              alt="DMCA.com Protection Status" 
              className="h-7 w-auto"
            />
          </a>
        </section>

      </div>
    </div>
  );
}
