import { QuizQuestion } from '@/types/quiz';
import {
  BLOOD_DROP_FLIGHT_DIAGRAM,
  ANGLE_OF_IMPACT_DIAGRAM,
  IMPACT_ANGLE_SERIES_DIAGRAM,
  AREA_OF_ORIGIN_DIAGRAM,
  DIRECTIONALITY_ANATOMY_DIAGRAM,
  CASTOFF_ARC_DIAGRAM,
  SWIPE_VS_WIPE_DIAGRAM,
  ARTERIAL_SPURT_DIAGRAM,
  SKELETONIZATION_DIAGRAM,
  SURFACE_TEXTURE_EFFECT_DIAGRAM,
  GUNSHOT_SPATTER_DIAGRAM,
  VOID_PATTERN_DIAGRAM
} from './bloodStainDiagrams';

export const BLOOD_STAIN_QUESTIONS: QuizQuestion[] = [
  {
    id: 'bpa-q1',
    question: 'High-speed photographic analyses and fluid mechanics demonstrate that an airborne blood droplet traveling through air maintains which geometric shape during free flight, and due to which primary physical force?',
    options: [
      'An elongated teardrop shape with a tapered trailing vertex, formed by continuous aerodynamic drag',
      'A flattened biconcave disc, generated by centrifugal rotational forces during detachment',
      'A spherical shape, maintained because cohesive intermolecular forces and surface tension pull the droplet into the minimum surface-area-to-volume geometry',
      'An inverted cone shape, caused by unequal gravitational acceleration between red cells and plasma'
    ],
    correctAnswerIndex: 2,
    explanation: 'Blood droplets in free flight are spherical, not teardrop-shaped. Blood has a high surface tension (~0.05 N/m). When a droplet separates from its source, cohesive forces and surface tension immediately pull oscillating fluid into an equilibrium sphere, which is the geometric shape that minimizes surface area for a given volume. The teardrop shape only exists momentarily while a drop clings to an emitter before falling.',
    points: 10,
    image: BLOOD_DROP_FLIGHT_DIAGRAM,
    imageCaption: 'Fluid dynamics of an airborne blood droplet in free flight vs. the teardrop misconception'
  },
  {
    id: 'bpa-q2',
    question: 'Refer to the diagram and trigonometric right-triangle derivation. If a forensic analyst measures an elliptical bloodstain on a vertical tile wall and finds a width (W) of 12.0 mm and a length (L, excluding the tapering tail) of 24.0 mm, what is the calculated angle of impact (θ) according to Balthazard\'s formula?',
    options: [
      'θ = 30°',
      'θ = 45°',
      'θ = 60°',
      'θ = 15°'
    ],
    correctAnswerIndex: 0,
    explanation: 'Under Victor Balthazard\'s (1939) trigonometric formula, the angle of impact is calculated as sin(θ) = Width / Length (excluding spines and tails). Here, sin(θ) = 12.0 mm / 24.0 mm = 0.50. The arcsin(0.50) is exactly 30° (or 30 degrees from the surface plane).',
    points: 10,
    image: ANGLE_OF_IMPACT_DIAGRAM,
    imageCaption: 'Balthazard (1939) angle of impact trigonometry: sin(θ) = Width (W) / Length (L)'
  },
  {
    id: 'bpa-q3',
    question: 'Examine the morphology spectrum below. As the impact angle of an airborne blood droplet decreases from 90° (perpendicular) down toward a glancing angle of 10°, what structural changes occur in the resulting bloodstain?',
    options: [
      'The stain remains circular but its diameter doubles at every 20-degree reduction',
      'The stain transitions from an essentially circular shape (W/L ≈ 1.0) with symmetrical scalloping into an increasingly elongated ellipse with a distinct, tapering tail pointing in the direction of travel',
      'The width expands while the length contracts, forming an oblate horizontal bar with bifurcated terminal edges',
      'The stain forms a concentric series of satellite rings with no discernible major or minor axis'
    ],
    correctAnswerIndex: 1,
    explanation: 'At 90° (perpendicular impact), blood strikes uniformly, producing an essentially circular stain with a width-to-length ratio near 1.0. As the angle decreases below 90°, the stain elongates along its major axis into an ellipse. At acute angles (≤30°), inertia propels a wave of blood forward, producing a narrow elongated tail and wave cast-off satellites that point in the direction of flight.',
    points: 10,
    image: IMPACT_ANGLE_SERIES_DIAGRAM,
    imageCaption: 'Progressive elongation and spine formation across 90°, 70°, 50°, 30°, and 10° impact angles'
  },
  {
    id: 'bpa-q4',
    question: 'In crime scene bloodstain reconstruction, what is the fundamental distinction between the "Area of Convergence" and the "Area of Origin"?',
    options: [
      'The Area of Convergence indicates the victim\'s post-mortem heart rate, whereas the Area of Origin establishes the weapon\'s mass',
      'The Area of Convergence is calculated exclusively using luminol, while the Area of Origin requires DNA STR profiling',
      'The Area of Convergence represents a 3D volume above the floor, while the Area of Origin is a 2D line on a single wall',
      'The Area of Convergence is a two-dimensional point/area on a planar surface where directional vectors intersect, whereas the Area of Origin is the three-dimensional location in space from which the blood source was projected'
    ],
    correctAnswerIndex: 3,
    explanation: 'The Area of Convergence is a 2D region on a planar surface (floor or wall) determined by tracing the long central axes of individual directional bloodstains back to where they cross. The Area of Origin is the 3D spatial location in space where the bloodshed actually occurred, established by calculating each stain\'s impact angle and projecting upward (e.g., using physical/virtual stringing or the tangent formula Height = distance × tan(θ)).',
    points: 10,
    image: AREA_OF_ORIGIN_DIAGRAM,
    imageCaption: 'Planar 2D Area of Convergence on floor vs. 3D spatial Area of Origin determined via stringing and tangent elevation'
  },
  {
    id: 'bpa-q5',
    question: 'Refer to the directional bloodstain diagram. When evaluating the flight path and leading edge of an elliptical impact bloodstain, how do forensic analysts identify the direction the droplet was traveling at the moment of impact?',
    options: [
      'The narrow, tapering tail and detached wave cast-off satellite spatters always point in the direction the droplet was traveling',
      'The blunt, rounded edge points in the direction of flight, while the tail points back toward the source',
      'The direction of travel is perpendicular to the major axis and points toward the widest scalloped edge',
      'Directionality cannot be determined from an individual stain without an accompanying footwear impression'
    ],
    correctAnswerIndex: 0,
    explanation: 'When an angled blood droplet strikes a surface, the blunt, rounded head marks the point of initial contact. Kinetic energy carries the remaining volume forward, drawing out a tapering tail, forward-projecting spines, and satellite spatter in the direction of travel (away from the blood source).',
    points: 10,
    image: DIRECTIONALITY_ANATOMY_DIAGRAM,
    imageCaption: 'Anatomy of a directional bloodstain: point of initial impact, parent stain, spines, and leading tapering tail'
  },
  {
    id: 'bpa-q6',
    question: 'Refer to the cast-off arc diagram. If a crime scene investigator identifies 4 distinct, parallel linear cast-off stain trails on a ceiling and adjacent wall, what is the scientifically defensible minimum number of blows delivered to the victim?',
    options: [
      'Exactly 3 blows',
      'Exactly 4 blows',
      'A minimum of 5 blows',
      'A minimum of 8 blows'
    ],
    correctAnswerIndex: 2,
    explanation: 'Under standard forensic principles, the first impact to an intact anatomical surface inflicts a wound and draws blood, but usually leaves the weapon clean (or does not yet have enough pooled blood to cast off). Blood must adhere to the weapon before centrifugal/tangential force can release cast-off arcs during subsequent swings. Therefore, the minimum number of blows delivered is calculated as (Number of Cast-Off Trails + 1). With 4 trails, the minimum blows delivered is 4 + 1 = 5.',
    points: 10,
    image: CASTOFF_ARC_DIAGRAM,
    imageCaption: 'Cast-off pattern mechanics from swinging weapon and the (N + 1) minimum blow rule'
  },
  {
    id: 'bpa-q7',
    question: 'In the classification of transfer bloodstains, how is a "Swipe" pattern definitively distinguished from a "Wipe" pattern?',
    options: [
      'A swipe is produced by high-velocity gunshot mist, whereas a wipe is produced by arterial spurting',
      'A swipe occurs when a blood-bearing object moves across an unstained surface, whereas a wipe occurs when an unstained object moves through an existing wet bloodstain',
      'A swipe is exclusively vertical under gravity, while a wipe is an exclusively horizontal capillary action',
      'A swipe completely dissolves underlying cellular DNA, while a wipe leaves erythrocytes intact'
    ],
    correctAnswerIndex: 1,
    explanation: 'According to SWGSTAIN/OSAC definitions, a Swipe pattern is the transfer of blood onto an unstained surface by a blood-bearing surface in lateral motion (characterized by a feathered trailing edge indicating movement). A Wipe pattern is created when an object moves through a pre-existing wet bloodstain on a surface, altering its margins and displacing the existing blood.',
    points: 10,
    image: SWIPE_VS_WIPE_DIAGRAM,
    imageCaption: 'Swipe pattern (bloody surface across clean target) vs. Wipe pattern (clean object displacing pre-existing bloodstain)'
  },
  {
    id: 'bpa-q8',
    question: 'Examine the arterial spurt diagram. Which physiological and fluid dynamic characteristics are pathognomonic of an arterial spray or gush pattern resulting from a severed carotid or femoral artery?',
    options: [
      'Uniform atomized mist (<0.1 mm) with zero vertical drainage and no pressure variation',
      'A collection of perfectly circular, non-overlapping drip stains with smooth margins',
      'A localized, dry transfer pattern mirroring the precise weave texture of the victim\'s clothing',
      'Undulating, wave-like zigzag trajectories reflecting ventricular systolic and diastolic pressure spikes, accompanied by high volume and prominent downward vertical gravity run-down'
    ],
    correctAnswerIndex: 3,
    explanation: 'Arterial spurts occur when an artery is breached while the heart is still pumping. Under systemic systolic blood pressure (~120 mmHg), blood is propelled outward in distinct rhythmic pulses, creating characteristic undulating or zigzag peak waveforms. The substantial blood volume released leads to heavy downward vertical runoff (gravity run-down), with peak heights typically diminishing as systemic blood pressure drops.',
    points: 10,
    image: ARTERIAL_SPURT_DIAGRAM,
    imageCaption: 'Hemodynamic waveform showing systolic pressure peaks (~120 mmHg) and vertical drainage runoff'
  },
  {
    id: 'bpa-q9',
    question: 'Which combination of morphological and biochemical findings serves as primary forensic evidence that a spatter pattern was caused by "expirated blood" rather than mechanical blunt-force impact?',
    options: [
      'Presence of micro-bubbles (vacuoles) that leave circular ring outlines, lighter or diluted color from mucus/saliva, and positive biochemical detection of salivary alpha-amylase',
      'Dense presence of heavy fibrin clots, high viscosity (>10 cP), and absence of salivary enzymes',
      'Droplets exhibiting 100% circular 90-degree geometry across all walls and ceiling surfaces',
      'Exclusively charred erythrocytes with complete absence of nucleated epithelial cells'
    ],
    correctAnswerIndex: 0,
    explanation: 'Expirated bloodstain patterns result from blood forced under respiratory pressure from the mouth, nose, or lungs (e.g., coughing, sneezing, or agonal breathing). Key diagnostic features include visible air bubbles/vacuoles (which rupture leaving clear circular centers or halos), dilution by saliva or mucous secretions causing a lighter pinkish appearance, and positive serological confirmation of human salivary alpha-amylase.',
    points: 10
  },
  {
    id: 'bpa-q10',
    question: 'Refer to the gunshot spatter diagram. When a high-velocity projectile (such as a rifle bullet) perforates a human head or limb, how do "forward spatter" and "backspatter" (blowback) typically compare in volume, dispersion, and origin?',
    options: [
      'Backspatter is always much larger in droplet size (>6 mm) and travels further than forward spatter',
      'Forward spatter emerges from the exit wound in the direction of bullet flight with greater droplet volume and a wider dispersion cone, whereas backspatter emanates from the entrance wound backward toward the firearm',
      'Forward spatter is projected backward toward the shooter, while backspatter only occurs when a silencer is mounted',
      'Forward and backspatter are identical in volume, velocity, and symmetrical spherical distribution'
    ],
    correctAnswerIndex: 1,
    explanation: 'Forward spatter originates from the exit wound and travels in the direction of projectile motion; it is typically characterized by a high volume of atomized, mist-like droplets (<1 mm) in a wide forward cone. Backspatter (or blowback) originates from the entrance wound and is projected backward toward the shooter/weapon, caused by muzzle gas expansion, subcutaneous temporary cavity collapse, and mechanical impact. Backspatter typically exhibits smaller overall volume and a narrower spatial distribution than forward spatter.',
    points: 10,
    image: GUNSHOT_SPATTER_DIAGRAM,
    imageCaption: 'High-velocity gunshot spatter dynamics: entrance backspatter vs. exit forward spatter cone'
  },
  {
    id: 'bpa-q11',
    question: 'Refer to the skeletonization chronology diagram. If a blood droplet deposited on a smooth linoleum kitchen floor is wiped 60 seconds after landing, why does an intact dark perimeter ring remain visible, and what does this prove to a forensic reconstructor?',
    options: [
      'The ring is caused by instant chemical etching of the linoleum wax by sodium chloride crystals',
      'The ring is formed by airborne fungal spores that colonize the boundary within 5 seconds',
      'Blood dries from the thinner outer edge inward within 30 to 90 seconds; a skeletonized ring proves that the droplet remained undisturbed for at least 30–90 seconds before the wiping motion occurred',
      'The ring is an optical illusion caused by oblique angle photography with alternate light sources'
    ],
    correctAnswerIndex: 2,
    explanation: 'Because the perimeter of a blood droplet is thinner than its domed center, it desiccates and adheres to the substrate first—typically within 30 to 90 seconds in standard ambient room conditions. If a wipe or disturbance occurs after this peripheral drying, the wet center is smeared away while the fixed outer ring persists. This "skeletonized stain" establishes a critical minimum time interval between blood shedding and subsequent movement or tampering.',
    points: 10,
    image: SKELETONIZATION_DIAGRAM,
    imageCaption: 'Drying sequence of a blood droplet: peripheral ring fixation (30-90s) and preserved skeletonized boundary after disturbance'
  },
  {
    id: 'bpa-q12',
    question: 'Examine the substrate texture diagram. When identical volumes of blood fall from the exact same height (1 meter) onto smooth plate glass versus rough, porous concrete, what fundamental difference is observed in droplet edge morphology?',
    options: [
      'The drop on concrete produces a perfectly smooth circular rim, while the drop on glass shatters into mist',
      'Both surfaces produce identical diameter stains with zero edge distortion',
      'The drop on glass evaporates in 2 seconds, preventing edge analysis',
      'The smooth non-porous glass produces a clean, sharp circular perimeter with minimal spines, whereas the rough concrete ruptures surface tension, producing irregular serrations, extensive spines, and dense satellite spatters'
    ],
    correctAnswerIndex: 3,
    explanation: 'Target surface texture and roughness have a profound influence on droplet impact morphology. Hard, smooth, non-porous surfaces (such as plate glass or glazed ceramic) absorb minimal energy and preserve droplet cohesion, resulting in clean, uniform margins. Rough, textured, or porous surfaces (like unfinished concrete, raw wood, or textured cardboard) disrupt cohesive forces on impact, creating ragged edges, extensive spines, and numerous satellite spatters.',
    points: 10,
    image: SURFACE_TEXTURE_EFFECT_DIAGRAM,
    imageCaption: 'Influence of target surface texture on edge scalloping, spines, and satellite spatter'
  },
  {
    id: 'bpa-q13',
    question: 'Refer to the crime scene diagram. An investigator observes a wide, dense impact spatter field across a living room wall, with a distinct, sharp-edged unstained outline in the shape of a high-backed armchair. This forensic phenomenon is classified as:',
    options: [
      'A Void Pattern, indicating an intermediate object blocked the spatter and was subsequently removed or moved',
      'A Cast-Off Pattern, indicating the assailant rotated the weapon 360 degrees',
      'A Latent Luminol Quenching Artifact, caused by iron-free drywall paint',
      'An Arterial Rain Shadow, caused by fluctuating systolic blood pressure'
    ],
    correctAnswerIndex: 0,
    explanation: 'A Void pattern is an absence of bloodstains within an otherwise continuous spatter or transfer field. It proves that an intermediate object (or person) was positioned between the blood source and the target wall during the bloodshed event, intercepting the spatter. Its presence allows investigators to reconstruct the exact shape, dimensions, and location of missing furniture, evidence, or individuals.',
    points: 10,
    image: VOID_PATTERN_DIAGRAM,
    imageCaption: 'Void pattern: unstained outline within a continuous spatter field created by intermediate object interception'
  },
  {
    id: 'bpa-q14',
    question: 'Regarding blood fluid dynamics and terminal velocity, at approximately what fall height does a free-falling human blood droplet reach its terminal velocity in air, and what happens to stain diameter as fall height increases beyond that point?',
    options: [
      'At 1 foot (0.3 meters), traveling at 5 ft/s; stain diameter continues to multiply indefinitely',
      'At approximately 20 to 25 feet (~7 to 8 meters), reaching ~25 ft/s (~7.6 m/s); beyond this height, stain diameter ceases to increase significantly on smooth surfaces',
      'At 100 feet (30 meters), traveling at Mach 1; stain diameter begins contracting due to kinetic re-compression',
      'Blood has no terminal velocity because red blood cells are denser than air and accelerate indefinitely'
    ],
    correctAnswerIndex: 1,
    explanation: 'As a blood droplet falls, gravitational downward acceleration is counterbalanced by upward air resistance (aerodynamic drag). It reaches terminal velocity at approximately 20 to 25 feet (~7 to 8 meters) of free fall, reaching a maximum speed of about 25.1 ft/s (7.65 m/s). Consequently, on smooth non-porous surfaces, the diameter of a passive drop increases with height up to ~7 meters, after which terminal velocity is reached and further increase in fall height causes no significant change in stain diameter.',
    points: 10
  },
  {
    id: 'bpa-q15',
    question: 'In crime scene investigation, why does luminol (or Bluestar) produce an intense blue chemiluminescent glow in the presence of latent or washed bloodstains, and which common domestic substance is famous for producing false-positive reactions?',
    options: [
      'Luminol reacts with salivary amylase through an endothermic cooling reaction; vinegar produces false positives',
      'Luminol binds to nuclear DNA histone octamers; motor oil causes false-positive luminescence',
      'The iron (heme) in blood hemoglobin catalyzes the alkaline oxidation of luminol by hydrogen peroxide, emitting light (~430–445 nm); household sodium hypochlorite bleach produces intense false positives',
      'Luminol undergoes radioactive decay when encountering potassium in platelets; distilled water causes false positives'
    ],
    correctAnswerIndex: 2,
    explanation: 'Luminol (3-aminophthalhydrazide) chemiluminescence relies on the peroxidase-like catalytic activity of iron ions (Fe²⁺/Fe³⁺) in hemoglobin. In an alkaline solution containing hydrogen peroxide, hemoglobin catalyzes the oxidation of luminol to an excited 3-aminophthalate dianion, which releases blue chemiluminescent light (λmax ~430–445 nm) as it relaxes to its ground state. Household bleach (sodium hypochlorite) strongly oxidizes luminol without blood, producing a rapid, intense false-positive chemiluminescence.',
    points: 10
  }
];
